### ISSUE TITLE
FreeCAD freezes on other manifest namespaces

### ISSUE THREAD

**Issue by PhoneDroid** [FreeCAD/AddonManager#2]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Problem description

If an addon has a namespace that isn't either `''` or  
`https://wiki.FreeCAD.org/Package_metadata`, the  
addon manager errors out and causes FreeCAD to  
freeze up.

As the Dracula preference pack just adopted the new  
manifest schema, it now not only fails to load it's schema  
but also causes FreeCAD to freeze up.
( The new schema has a different namespace )

### Full version info

```shell
OS: Ubuntu 24.04.2 LTS (KDE/plasmawayland/wayland)
Architecture: x86_64
Version: 1.1.0dev.40971 (Git)
Build date: 2025/03/24 18:02:34
Build type: Release
Branch: main
Hash: b33c2363226a5fc1e8222a02659118c95e1a5119
Python 3.12.3, Qt 5.15.13, Coin 4.0.2, Vtk 9.1.0, OCC 7.8.1
Locale: English/United States (en_US)
Stylesheet/Theme/QtStyle: unset/FreeCAD Classic/Qt default
Logical DPI/Physical DPI/Pixel Ratio: 96/80.9812/1
Installed mods: 
  * SelectorToolbar
```

### Subproject(s) affected?

Addon Manager

### Anything else?

![Image](https://github.com/user-attachments/assets/765a7349-96c2-4bd0-83f1-dc3680a9cc1b)

I propose the addon manager doesn't have a hardcoded  
namespace, instead it should use whatever namespace  
is present and parse with that.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by chennes** [comment]
Fixed by df5d87bb6d3f8743118216da9d69a28776aa7dbb

**Comment by PhoneDroid** [comment]
@chennes Thank you very much!

I'm still failing to properly compile FC,  
hope I can get it fixed soon so I can make  
this kind of fixes myself ..
